name: Project Application
description: Apply to a project
title: "Application: [Your Name] for [Project Name]"
labels: [application]
body:
  - type: input
    id: name
    attributes:
      label: Full Name
      description: "Your full legal name for identification."
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email
      description: "Your university email address."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Why are you interested in this project?
      description: |
        Explain why you chose this project. Is it the topic, method, or relevance to your future goals?
        Mention academic, personal, or career motivations. Be specific.
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Relevant background
      description: |
        Briefly describe coursework, tools, or experience that prepare you for this project.
        Include relevant modules, coding tools, research experience, or domain knowledge.
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Questions (optional)
      description: |
        Use this space to ask about project scope, expectations, datasets, etc.
        All questions and answers will be public to benefit others.

  - type: checkboxes
    id: consent
    attributes:
      label: Consent
      options:
        - label: I understand this is a public submission and not a guarantee of acceptance
          required: true
