name: Update Project Status

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # manual run

jobs:
  update-status:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to update status.md
        run: python .github/scripts/update_status.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add status.md
          git commit -m "🔁 Auto-update status.md" || echo "No changes to commit"
          git push
